HeadNode:
  LocalStorage:
    RootVolume:
      Size: 100
      Encrypted: false
      VolumeType: gp3
      Iops: 3000
      Throughput: 250
  CustomActions:
    OnNodeConfigured:
      Args:
        - 03.configure.slurm.acct.headnode.sh
        - 04.configure.slurm.AllOrNothing.headnode.sh
        - 05.install.ldap.server.headnode.sh
        - 06.install.ldap.client.sh
        - 07.configure.slurm.tagging.headnode.sh
        - 10.install.enginframe.headnode.sh
        - 11.customize.enginframe.headnode.sh
        - 12.configure.enginframe.alb.headnode.sh
        - 20.install.dcv.slurm.headnode.sh
        - 40.install.monitoring.headnode.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
    S3Access:
      - BucketName: '*'
        EnableWriteAccess: true
  InstanceType: m6i.2xlarge
  Networking:
    AdditionalSecurityGroups:
      - ${ADDITIONAL_SG}
    ElasticIp: ${USE_PUBLIC_IPS}
    SubnetId: ${SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  Imds:
    Secured: false
Image:
  Os: alinux2
Region: ${AWS_REGION_NAME}
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
  SlurmQueues:
    - Name: high
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: high-c6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: high-m6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: high-r6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: high-m5zn-12xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5zn.12xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: low
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: low-c5n-18xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c5n.18xlarge
          MaxCount: 300
          MinCount: 0
        - Name: low-m5n-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5n.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: low-r5n-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r5n.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: low-disk
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: low-m5dn-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5dn.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: low-r5dn-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r5dn.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: low-z1d-12xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: z1d.12xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: old
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: low-c5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: low-m5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: low-r5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: old-disk
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: low-m5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5d.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: low-r5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5d.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: dcv-gpu
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: dcv-gpu-g4dn-xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.xlarge
          MaxCount: 100
          MinCount: 0
        - Name: dcv-gpu-g4dn-2xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.2xlarge
          MaxCount: 100
          MinCount: 0
        - Name: dcv-gpu-g4dn-4xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.4xlarge
          MaxCount: 100
          MinCount: 0
        - Name: dcv-gpu-g4dn-8xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.8xlarge
          MaxCount: 100
          MinCount: 0
        - Name: dcv-gpu-g4dn-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.16xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 25.install.dcv-server.gpu.sh
            - 26.configure.dcv.alb.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: dcv
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: dcv-m6-32xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.32xlarge
          Efa:
            Enabled: true
          MaxCount: 200
          MinCount: 0
        - Name: dcv-m6i-2xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.2xlarge
          MaxCount: 200
          MinCount: 0
        - Name: dcv-m6i-8xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.8xlarge
          MaxCount: 200
          MinCount: 0
        - Name: dcv-m6i-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.16xlarge
          MaxCount: 200
          MinCount: 0
        - Name: dcv-m6i-xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.xlarge
          MaxCount: 200
          MinCount: 0          
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 25.install.dcv-server.compute.sh
            - 26.configure.dcv.alb.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: spot-high
      CapacityType: SPOT
      ComputeResources:
        - Name: spot-high-c6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: spot-high-m5zn-12xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5zn.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: spot-high-m6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: spot-high-r6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r6i.32xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: spot-low
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: spot-low-c5n-18xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c5n.18xlarge
          MaxCount: 300
          MinCount: 0
        - Name: spot-low-c5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: spot-low-m5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: spot-low-r5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: spot-low-z1d-12xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: z1d.12xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 06.install.ldap.client.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
SharedStorage:
${FSX}
Tags:
  - Key: EnginFrame
    Value: 'true'
  - Key: 1Click-HPC
    Value: 'true'
  - Key: 1Click-HPC-version
    Value: '0.3'