HeadNode:
  LocalStorage:
    RootVolume:
      Size: 2000
      Encrypted: false
      VolumeType: gp3
      Iops: 10000
      Throughput: 1000
  CustomActions:
    OnNodeConfigured:
      Args:
        - 00.install.custom.packages.headnode.sh
        - 01.install.disk.quota.headnode.sh
        - 02.activate.passwordless.AD.headnode.sh
        - 03.configure.slurm.acct.headnode.sh
        - 04.configure.slurm.AllOrNothing.headnode.sh
        - 07.configure.slurm.tagging.headnode.sh
        - 10.install.enginframe.headnode.sh
        - 12.configure.enginframe.alb.headnode.sh
        - 20.install.dcv.slurm.headnode.sh
        - 40.install.monitoring.headnode.sh
        - 45.customize.splashpage.headnode.sh
        - 50.install.capacity.reservation.pool.sh
        - 70.install.enroot.pyxis.sh
        - 100.reboot.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/${CLUSTER_NAME}-ODCR-Policy
      - Policy: arn:aws:iam::842865360552:policy/Stability_CreateTags_Policy
    S3Access:
      - BucketName: '*'
        EnableWriteAccess: true
  InstanceType: c5n.18xlarge
  Networking:
    AdditionalSecurityGroups:
      - ${ADDITIONAL_SG}
    ElasticIp: true
    SubnetId: ${HN_SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  Imds:
    Secured: false
Image:
  Os: alinux2
DirectoryService:
  DomainName: dc=${DC0},dc=${DC1},dc=${DC2}
  DomainAddr: ldaps://${NLB_PUBLIC_DNS_NAME}
  PasswordSecretArn: ${SECRET_ARN}
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=Users,ou=${OU},dc=${DC0},dc=${DC1},dc=${DC2}
  LdapTlsReqCert: never
Region: ${AWS_REGION_NAME}
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
  SlurmQueues:
    - Name: compute-od-cpu
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: c6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5zn-12xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5zn.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: x2iezn-12xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: x2iezn.12xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 00.install.knot.resolver.cpu.sh
            - 04.configure.disable.anacron.compute.sh
            - 40.install.monitoring.compute.sh
            - 70.install.singularity.compute.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::842865360552:policy/Stability_CreateTags_Policy
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: compute-od-gpu
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: p4d-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: p4d.24xlarge
          MaxCount: 194
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 35.add.nvidia.udev.rules.gpu.sh
            - 35.boost.gpu.clock.gpu.sh
            - 40.install.monitoring.compute.sh
            - 45.install.nccl.compute.sh
            - 60.install.gpumon.cloudwatch.metrics.sh
            - 70.install.enroot.pyxis.sh
            - 70.install.singularity.compute.sh
            - 80.fast.aws.cli.compute.sh
            - 90.allow.nvidia.debug.gpu.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::842865360552:policy/Stability_CreateTags_Policy
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: compute-od-jupyter
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 256
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: p4d-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: p4d.24xlarge
          MaxCount: 20
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 35.add.nvidia.udev.rules.gpu.sh
            - 35.boost.gpu.clock.gpu.sh
            - 40.install.monitoring.compute.sh
            - 45.install.nccl.compute.sh
            - 60.install.gpumon.cloudwatch.metrics.sh
            - 80.fast.aws.cli.compute.sh
            - 85.install.jupiter.notebook.gpu.sh
            - 90.allow.nvidia.debug.gpu.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::842865360552:policy/Stability_CreateTags_Policy
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: compute-od-mig
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
            Encrypted: false
            VolumeType: gp3
            Iops: 5000
      ComputeResources:
        - Name: p4d-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: p4d.24xlarge
          MaxCount: 16
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 35.add.nvidia.udev.rules.gpu.sh
            - 35.boost.gpu.clock.gpu.sh
            - 40.install.monitoring.compute.sh
            - 45.install.nccl.compute.sh
            - 60.install.gpumon.cloudwatch.metrics.sh
            - 70.install.enroot.pyxis.sh
            - 70.install.singularity.compute.sh
            - 80.fast.aws.cli.compute.sh
            - 90.allow.nvidia.debug.gpu.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::842865360552:policy/Stability_CreateTags_Policy
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: compute-spot-cpu
      CapacityType: SPOT
      ComputeResources:
        - Name: m5zn-12xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5zn.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: c6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r6i.32xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.custom.packages.compute.sh
            - 04.configure.disable.anacron.compute.sh
            - 40.install.monitoring.compute.sh
            - 70.install.singularity.compute.sh
            - 80.fast.aws.cli.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::842865360552:policy/Stability_CreateTags_Policy
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
SharedStorage:
${FSX}
Tags:
  - Key: EnginFrame
    Value: 'true'
  - Key: 1Click-HPC
    Value: 'true'
  - Key: 1Click-HPC-version
    Value: '0.4'
  - Key: map-migrated
    Value: ${MAP_MIGRATED}