HeadNode:
  LocalStorage:
    RootVolume:
      Size: 100
      Encrypted: false
      VolumeType: gp3
      Iops: 3000
      Throughput: 250
  CustomActions:
    OnNodeConfigured:
      Args:
        - 04.configure.slurm.AllOrNothing.headnode.sh
        - 07.configure.slurm.tagging.headnode.sh
        - 10.install.enginframe.headnode.sh
        - 12.configure.enginframe.alb.headnode.sh
        - 20.install.dcv.slurm.headnode.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
    S3Access:
      - BucketName: '*'
        EnableWriteAccess: true
  InstanceType: m6i.2xlarge
  Networking:
    AdditionalSecurityGroups:
      - ${ADDITIONAL_SG}
      - ${DB_SG}
    ElasticIp: true
    SubnetId: ${PRIVATE_SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  Imds:
    Secured: false
Image:
  Os: alinux2
DirectoryService:
  DomainName: dc=corp,dc=pcluster,dc=com
  DomainAddr: ${NLB_PUBLIC_DNS_NAME}
  PasswordSecretArn: ${SECRET_ARN}
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=Users,ou=CORP,dc=corp,dc=pcluster,dc=com
  LdapTlsReqCert: never
Region: ${AWS_REGION_NAME}
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    EnableMemoryBasedScheduling: true
    Database:
      Uri: ${SLURM_DB_ENDPOINT}
      UserName: 'admin'
      PasswordSecretArn: ${SECRET_ARN}
  SlurmQueues:
    - Name: compute-od-1
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: hpc6a-48xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: hpc6a.48xlarge
          MaxCount: 300
          MinCount: 0
        - Name: hpc6id-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: hpc6id.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: c6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r6i.32xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: compute-od-2
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: c5n-18xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c5n.18xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5zn-12xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5zn.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: m5n-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5n.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5n-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r5n.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: x2iedn-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: x2iedn.32xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: compute-od-3
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: m5dn-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5dn.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5dn-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r5dn.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: compute-od-4
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: c5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: compute-od-5
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: c5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5d.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5d.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5d.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: compute-spot-1
      CapacityType: SPOT
      ComputeResources:
        - Name: m5zn-12xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m5zn.12xlarge
          MaxCount: 100
          MinCount: 0
        - Name: c6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: m6i.32xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r6i-32xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r6i.32xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: compute-spot-2
      CapacityType: SPOT
      ComputeResources:
        - Name: c5n-18xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c5n.18xlarge
          MaxCount: 300
          MinCount: 0
        - Name: c5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: z1d-12xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: z1d.12xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: dcv-gpu
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: g4dn-xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-2xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.2xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-4xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.4xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-8xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.8xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.16xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 25.install.dcv-server.gpu.sh
            - 26.configure.dcv.alb.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
    - Name: dcv
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: m6i-32xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.32xlarge
          Efa:
            Enabled: true
          MaxCount: 200
          MinCount: 0
        - Name: m6i-2xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.2xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m6i-8xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.8xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m6i-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.16xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m6i-xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m6i.xlarge
          MaxCount: 200
          MinCount: 0          
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 25.install.dcv-server.compute.sh
            - 26.configure.dcv.alb.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${PRIVATE_SUBNET_ID}
        AssignPublicIp: false
SharedStorage:
${FSX}
Tags:
  - Key: EnginFrame
    Value: 'true'
  - Key: 1Click-HPC
    Value: 'true'
  - Key: 1Click-HPC-version
    Value: '0.4'