#
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
#
version: '3.8'
services:
    prometheus-node-exporter:
        container_name: node-exporter
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
        image: quay.io/prometheus/node-exporter
        command:
            - '--path.rootfs=/host'
    dcgm-exporter:
        container_name: nvidia-dcgm
        network_mode: host
        pid: host
        restart: unless-stopped
        image: nvidia/dcgm-exporter
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all